#!/usr/bin/env python3
"""
Reorg-12 Phase A — rebuild REGISTRY.md from doc front-matter.

Scans every `.md` file with front-matter under product/, planning/, development/,
standards/, playbooks/, skills/ and emits a table grouped by layer prefix
(why / what / how) with columns: ID | Path | Purpose | Status.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ["product", "planning", "development", "standards", "playbooks", "skills"]
EXCLUDE_DIRS = {"_attic", "_inbox", "archive", "node_modules", ".git"}

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$")


def parse_frontmatter(text: str) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        km = KEY_RE.match(line)
        if km:
            out[km.group(1)] = km.group(2).strip()
    return out


def should_scan(path: Path) -> bool:
    parts = set(path.parts)
    if parts & EXCLUDE_DIRS:
        return False
    return path.suffix == ".md"


def layer_of(doc_id: str) -> str:
    if doc_id.startswith("why-"):
        return "why"
    if doc_id.startswith("what-"):
        return "what"
    return "how"


def main():
    rows = []
    for scan_dir in SCAN_DIRS:
        base = ROOT / scan_dir
        if not base.exists():
            continue
        for path in base.rglob("*.md"):
            if not should_scan(path):
                continue
            text = path.read_text()
            fm = parse_frontmatter(text)
            if not fm:
                continue
            doc_id = fm.get("id", "")
            if not doc_id:
                print(f"WARN: missing id: {path.relative_to(ROOT)}", file=sys.stderr)
                continue
            rows.append({
                "id": doc_id,
                "path": path.relative_to(ROOT).as_posix(),
                "purpose": fm.get("purpose", "").strip('"').strip("'"),
                "status": fm.get("status", ""),
                "layer": layer_of(doc_id),
            })

    rows.sort(key=lambda r: (r["layer"], r["id"]))
    by_layer = {"why": [], "what": [], "how": []}
    for r in rows:
        by_layer[r["layer"]].append(r)

    out = []
    out.append("---")
    out.append("id: how-registry")
    out.append("purpose: Catalog of every narrative doc with stable id, path, and purpose.")
    out.append("layer: how")
    out.append("status: active")
    out.append("---")
    out.append("")
    out.append("# Document registry")
    out.append("")
    out.append(f"> {len(rows)} docs catalogued. Generated by `scripts/rebuild-registry.py` from each doc's YAML front-matter.")
    out.append("> Every narrative doc carries a stable `id:` (`why-` / `what-` / `how-`). Refs may use either the file path or the id; both resolve here.")
    out.append("> Re-generate after any doc add / remove / id change.")
    out.append("")

    for layer_key, layer_title in [
        ("why", "WHY — foundation"),
        ("what", "WHAT — needs · systems · capabilities · ui · exploration · specs · products"),
        ("how", "HOW — planning · development · standards · playbooks · skills"),
    ]:
        layer_rows = by_layer[layer_key]
        out.append(f"## {layer_title}")
        out.append("")
        out.append(f"_{len(layer_rows)} docs._")
        out.append("")
        out.append("| ID | Path | Purpose | Status |")
        out.append("|---|---|---|---|")
        for r in layer_rows:
            purpose = r["purpose"].replace("|", "\\|")
            out.append(f"| `{r['id']}` | `{r['path']}` | {purpose} | {r['status']} |")
        out.append("")

    (ROOT / "REGISTRY.md").write_text("\n".join(out))
    print(f"Wrote REGISTRY.md — {len(rows)} docs (why={len(by_layer['why'])}, what={len(by_layer['what'])}, how={len(by_layer['how'])}).")


if __name__ == "__main__":
    main()
